version: "3.5"
services:
  web:
    image: bref/fpm-dev-gateway
    ports:
      - '3000:80'
    volumes:
      - ./app:/var/task:ro
    links:
      - php
    environment:
      HANDLER: public/index.php
      DOCUMENT_ROOT: public
  php:
    image: bref/php-80-fpm-dev
    volumes:
      - ./app:/var/task:ro
    depends_on:
      - dynamodb-local
  composer:
    image: composer/composer:2
    command: install
    volumes:
      - ./app:/app
  dynamodb-local:
    build:
      context: .
      dockerfile: DockerfileDynamoDbLocal
  dynamodb-admin:
    build:
      context: .
      dockerfile: DockerfileDynamoDbAdmin
    depends_on:
      - dynamodb-local
    ports:
      - "8000:8001"
