version: "3.5"
services:
  web:
    image: bref/fpm-dev-gateway
    ports:
      - 3000:80
    volumes:
      - ./app:/var/task:ro
    links:
      - php
    environment:
      HANDLER: public/index.php
      DOCUMENT_ROOT: public
  php:
    image: bref/php-80-fpm-dev
    volumes:
      - ./app:/var/task
    depends_on:
      - dynamodb-local
  composer:
    image: composer/composer:2
    command: install
    volumes:
      - ./app:/app
  yarn-dev:
    build:
      context: ./Dockerfiles
      dockerfile: Yarn
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
    command:
      - yarn
      - dev
  dynamodb-local:
    build:
      context: ./Dockerfiles
      dockerfile: DynamoDbLocal
  dynamodb-admin:
    build:
      context: ./Dockerfiles
      dockerfile: DynamoDbAdmin
    depends_on:
      - dynamodb-local
    ports:
      - 3001:8001
#  amazon-sqs:
#    image: roribio16/alpine-sqs:latest
#    container_name: amazon-sqs
#    ports:
#      - "9324:9324" #TODO : remove
#      - "9325:9325"
#    stdin_open: true
#    tty: true
  amazon-sqs:
    image: roribio16/alpine-sqs
    ports:
      - "9325:9325"
    volumes:
      - ./elasticmq.conf:/opt/config/elasticmq.conf
