parameters:
    app.stage: "%env(resolve:APP_STAGE)%"
    aws.deployment.region: "%env(resolve:AWS_DEPLOYMENT_REGION)%"
    app.name: "sushi-doctor" # Never change
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $appStage: '%app.stage%'
            $appName: '%app.name%'
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
