parameters:
    app.stage: "%env(string:APP_STAGE)%"
    app.secret: "%env(string:APP_SECRET)%"
    app.env: "%env(string:APP_ENV)%"
    jwt.keys.directory: "%kernel.project_dir%/%env(string:JWT_KEYS_DIRECTORY)%"
    jwt.cookie.secure: "%env(bool:JWT_COOKIE_SECURE)%"
    jwt.cookie.path: "/api"
    jwt.cookie.bearer.ttl: 900
    jwt.cookie.refresh.ttl: 3600
    aws.key: "%env(string:AWS_KEY)%"
    aws.secret: "%env(string:AWS_SECRET)%"
    aws.deployment.region: "%env(string:AWS_DEPLOYMENT_REGION)%"
    aws.dynamodb.endpoint: "%env(string:AWS_DYNAMO_DB_ENDPOINT)%"
    aws.queue.id: '%env(AWS_QUEUE_ID)%'

    table.prefix: !php/const DYNAMODB_TABLE_PREFIX
services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $appEnv: '%app.env%'
            $appStage: '%app.stage%'
            $jwtCookieRefreshTtl: '%jwt.cookie.refresh.ttl%'
            $jwtCookiePath: '%jwt.cookie.path%'
            $jwtCookieSecure: '%jwt.cookie.secure%'
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
    JLucki\ODM\Spark\Spark:
        $version: 'latest'
        $region: '%aws.deployment.region%'
        $endpoint: '%aws.dynamodb.endpoint%'
        $key: '%aws.key%'
        $secret: '%aws.secret%'
    app.refreshservice:
        class: App\Security\RefreshService
        public: true
        arguments: [ "@gesdinet.jwtrefreshtoken" ]
    Bref\Symfony\Messenger\Service\Sqs\SqsConsumer:
        public: true
        autowire: true
        arguments:
            # Pass the transport name used in config/packages/messenger.yaml
            $transportName: 'async'
