framework:
    messenger:
        transports:
#            async: 'https://sqs.%aws.deployment.region%.amazonaws.com/%aws.queue.id%/%app.name%_%app.stage%_queue'
#            async: 'https://sqs.eu-west-1.amazonaws.com/907147359096/sushi-doctor_production_queue?access_key=%aws.key%&secret_key=%aws.secret%&region=%aws.deployment.region%'
            async: 'https://sqs.eu-west-1.amazonaws.com/907147359096/sushi-doctor_production_queue'
        routing:
            App\Message\SmsNotification: async


#MESSENGER_TRANSPORT_DSN=https://AKIAIOSFODNN7EXAMPLE:j17M97ffSVoKI0briFoo9a@sqs.eu-west-3.amazonaws.com/123456789012/messages
