framework:
    messenger:
        transports:
            async: 'https://sqs.%aws.deployment.region%.amazonaws.com/%aws.queue.id%/%app.name%_%app.stage%_queue'
#            async: 'https://sqs.eu-west-1.amazonaws.com/907147359096/sushi-doctor_production_queue'
        routing:
            App\Message\SmsNotification: async
