aws:
    version: latest
    region: '%aws.deployment.region%'
    credentials:
        key: "%env(AWS_KEY)%"
        secret: "%env(AWS_SECRET)%"
    DynamoDb:
        region: '%aws.deployment.region%'
        endpoint: 'http://dynamodb-local:8000'
    S3:
        version: '2006-03-01'
