aws:
    version: latest
    region: '%aws.deployment.region%'
    credentials:
        key: '%aws.key%'
        secret: '%aws.secret%'
#    S3:
#        version: '2006-03-01'
    Sqs:
        credentials:
            key: '%aws.key%'
            secret: '%aws.secret%'
#    CloudSearchDomain:
#        endpoint: https://search-with-some-subdomain.us-east-1.cloudsearch.amazonaws.com
