gesdinet_jwt_refresh_token:
  ttl: '%jwt.cookie.refresh.ttl%'
  user_identity_field: email
  firewall: api
  user_provider: App\Security\UserProvider
  object_manager: App\Security\RefreshTokenObjectManager
  refresh_token_class: App\RefreshToken\JwtRefreshToken
  ttl_update: true
