gesdinet_jwt_refresh_token:
  ttl: 2592000 # TODO : Import param
  user_identity_field: email
  firewall: api
  user_provider: App\Security\UserProvider
  object_manager: App\Security\RefreshTokenObjectManager
  refresh_token_class: App\RefreshToken\JwtRefreshToken
