lexik_jwt_authentication:
    secret_key: '%jwt.keys.directory%/private.pem'
    public_key: '%jwt.keys.directory%/public.pem'
    pass_phrase: '%app.secret%'
    token_ttl: 900 # TODO: import param
    token_extractors:
        cookie:
            enabled: true
            name: BEARER
    set_cookies:
        BEARER:
            samesite: lax
            path: /api # TODO : Import param
            secure: '%jwt.cookie.secure%'
            httpOnly: true


