name: Test
on:
  push:
    branches: [main, preprod, dev]
defaults:
  run:
    working-directory: ./app
jobs:
  lint-front:
    name: 'React: Eslint'
    runs-on: Ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Eslint
      run: yarn install && yarn lint
  lint-back:
    name: 'PHP: CS, STAN, Unit'
    runs-on: Ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Eslint
      run: yarn install && yarn lint
